language: go

sudo: false
go:
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/torbit/cdb

script:
    - $HOME/gopath/bin/goveralls -repotoken bxOLfRVZ3qtAkjOntFicuSVZvZmAmsK3P

install:
    - go get -d -v ./...
    - go build -v ./...
